title: Bärenbude
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Bärenbude
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "private Projektseite — noch im Aufbau"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.4.0

exclude:
  - README.md
  - vendor
  - Gemfile

defaults:
# Define here metadata attributes of pages for all of them at once of on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

theme_variables: 
  # git_host: GitHub
  # back_to_top: true
  # privacy_statement_url: /privacy
  # github_buttons: 
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # toc:
  #   min_headers: 2
  #   headers: 'h2'
  # topnav:
    # theme: light
    # brand_logo: assets/img/main_logo.svg
    # github: true
    # twitter: false
  # theme_color: 0d6efd
  # fonts:
  #   - url towards a font

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

